services:
  ur5:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ur5_ws
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
    volumes:
      - .:/workspace_ur5
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/dri:/dev/dri
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB0:/dev/ttyUSB1
    stdin_open: true
    tty: true
